# Generated by Django 6.0.6 on 2026-06-19 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mesas', '0001_initial'),
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evento', models.CharField(choices=[('pedido_creado', 'Pedido creado'), ('cambio_estado', 'Cambio de estado'), ('pedido_entregado', 'Pedido entregado')], max_length=30)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_evento', models.DateTimeField(auto_now_add=True)),
                ('mesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='mesas.mesa')),
                ('pedido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='pedidos.pedido')),
            ],
        ),
    ]
