# Generated by Django 6.0.5 on 2026-07-20 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metricas', '0001_initial'),
        ('pedidos', '0002_pedido_fin_registro_pedido_inicio_registro_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('tiempo_captura_ms', models.PositiveIntegerField()),
                ('tiempo_procesamiento_ms', models.PositiveIntegerField()),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs_metricas', to='pedidos.pedido')),
            ],
            options={
                'db_table': 'log_pedidos',
                'ordering': ['-timestamp'],
            },
        ),
    ]
