# Generated by Django 6.0.6 on 2026-07-20 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesa',
            name='qr_imagen',
            field=models.ImageField(blank=True, null=True, upload_to='qr_mesas/'),
        ),
    ]
